on:
  push:
jobs:
  test_unit:
    name: unitaire
    strategy:
      matrix:
        version: ["1.17","1.18","1.19"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name:  go dependancies
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.version}}
      - name: install 
        run: go get .
      - name: test
        run: go test ./...