on:
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with: 
          go-version: '1.18'
      - run: go get .
      - name: windows 
        run: |
             env GOOS=windows GOARCH=amd64 go build -o .
             env GOOS=linux GOARCH=amd64 go build -o .
             ls
             echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Connect to Docker Hub
        uses: docker/login-action@v2
        with: # by default the registry is the docker hub
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/coucou:${{env.version}}

      



        
    