on:
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        with: 
          go-version: '1.18'
        run: go get .
      - name: windows 
        run: |
             venv GOOS=windows GOARCH=amd64 go build runs-o
             venv GOOS=linus GOARCH=amd64 go build runs-o
      



        
    