on:
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with: 
          go-version: '1.18'
      - run: go get .
      - name: windows 
        run: |
             env GOOS=windows GOARCH=amd64 go build -o .
             env GOOS=linux GOARCH=amd64 go build -o .
             ls

      



        
    